###################################################
# Visualization of detector geometry and events  
###################################################

/tracking/storeTrajectory 1
#/tracking/verbose 1

/vis/scene/create
/vis/scene/add/volume WorldVisible

#/vis/geometry/set/daughtersInvisible World -1 0
#/vis/geometry/set/visibility CalorimeterLeft 3 1

# Create a scene handler for a specific graphics system
/vis/open OIX 800x800-0+0

# draw scene
/vis/viewer/zoom 1.4
/vis/viewer/set/viewpointThetaPhi 90 90
/vis/viewer/set/style wireframe
/vis/geometry/set/visibility all -1 true
/vis/geometry/set/daughtersInvisible all -1 false
#/vis/geometry/set/visibility vCalorimeter ! true
/vis/geometry/set/colour vMonitor ! 0.4 1.0 0.6
/vis/geometry/set/colour vTarget ! 0.4 1.0 0.6
/vis/geometry/set/colour vTargetInnerCover ! 0.4 1.0 0.6
#/vis/viewer/set/hiddenEdge 0

/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/select drawByParticleID-0
/vis/modeling/trajectories/drawByParticleID-0/setRGBA gamma 0.8 0.8 1.0 1
/vis/modeling/trajectories/drawByParticleID-0/setRGBA neutron 0.5 0.5 0.2 1
/vis/modeling/trajectories/drawByParticleID-0/setRGBA pi- 1.0 0.0 0.0 1
/vis/modeling/trajectories/drawByParticleID-0/setRGBA e- 0.3 0.3 0.8 1
/vis/modeling/trajectories/drawByParticleID-0/setRGBA e+ 0.8 0.3 0.3 1

#/vis/scene/add/trajectories
#/vis/scene/add/hits
#/vis/scene/add/axes

/cexmc/vis/verbose 2
/cexmc/vis/drawTrajMarkers false

/vis/viewer/flush

/vis/scene/endOfEventAction accumulate 10
