#!/bin/sh
# shows job progress at gridengine queues

CEXMC_PREFIX=cexmc_

qstat -u $USER

jobids=`qstat -u $USER | sed '1,2d' | grep $CEXMC_PREFIX | awk '{print $1}'`
jobbasenames=`qstat -u $USER -r | grep 'Full jobname' | grep $CEXMC_PREFIX | awk '{print $3}'`
jobnames=""

i=1
for jobbasename in $jobbasenames ; do
    jobnames=$jobnames' '$jobbasename.o`echo $jobids | awk "{print \\$$i}"`
    (( ++i ))
done

i=1
echo ---------------
for job in $jobnames ; do
    ordered=`head -120 $job | awk '/^\/run\/beamOn/ {print $2}'`
    current=`tail -120 $job | grep ^Event | tail -1 | awk '{print $2}'`
    jobbasename=`echo $jobbasenames | awk "{print \\$$i}"`
    jobbasename=${jobbasename/$CEXMC_PREFIX/}
    jobbasename=${jobbasename/\.job/}
    fdbsize=`du -sh $CEXMC_PROJECTS_DIR/$jobbasename.fdb | awk '{print $1}'`
    edbsize=`du -sh $CEXMC_PROJECTS_DIR/$jobbasename.edb | awk '{print $1}'`
    echo $job:  $(( current * 100 / ordered ))%,    fdb: $fdbsize, edb: $edbsize
    (( ++i ))
done

